export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const POST_LOADING = 'POST_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const GET_SHOPINGFILE = "GET_SHOPINGFILE";
export const SHOPINGFILE_LOADING = "SHOPINGFILE_LOADING";
export const SHOPING_NOT_FOUND = "SHOPING_NOT_FOUND";
export const CLEAR_CURRENT_SHOPINGFILE = "CLEAR_CURRENT_SHOPINGFILE";
export const GET_SHOPINGFILES = "GET_SHOPINGFILES";

export const DELETE_SHOPING="DELETE_SHOPING";
export const UPDATE_SHOPING="UPDATE_SHOPING";
export const ADD_SHOPINGFILE="ADD_SHOPINGFILE";

export const BUSCA_SHOPING="BUSCA_SHOPING";




export const GET_CATEGORIAFILE = "GET_CATEGORIAFILE";
export const CATEGORIAFILE_LOADING = "CATEGORIAFILE_LOADING";
export const CATEGORIA_NOT_FOUND = "CATEGORIA_NOT_FOUND";
export const CLEAR_CURRENT_CATEGORIAFILE = "CLEAR_CURRENT_CATEGORIAFILE";
export const GET_CATEGORIAFILES = "GET_CATEGORIAFILES";

export const DELETE_CATEGORIA="DELETE_CATEGORIA";
export const UPDATE_CATEGORIA="UPDATE_CATEGORIA";
export const ADD_CATEGORIAFILE="ADD_CATEGORIAFILE";

export const BUSCA_CATEGORIA="BUSCA_CATEGORIA";


export const SET_LOGGED_IN_USER = "SET_LOGGED_IN_USER";
export const LOGOUT = "LOGOUT";



